version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: ["./wait-for-db.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file: .env
volumes:
  pgdata: